name: Infer#

on:
  push:
    branches: [ master, feat/**, release/** ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

env:
  DOTNET_VERSION: net9.0

jobs:
  infer:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        configuration: [ 'Debug' ]
        runtime-identifier: [ 'win-x64' ]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET 9.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        cache: true
        cache-dependency-path: |
          src/ISTA-Patcher/packages.lock.json
          src/ISTAlter/packages.lock.json

    - name: Publish the application
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: |
        dotnet build src/ISTA-Patcher --configuration ${{ matrix.configuration }} --runtime ${{ matrix.runtime-identifier }} --no-self-contained
        rm -f 'src/ISTA-Patcher/bin/${{ matrix.configuration }}/${{ env.DOTNET_VERSION }}/${{ matrix.runtime-identifier }}/LibGit2Sharp.dll'
        rm -f 'src/ISTA-Patcher/bin/${{ matrix.configuration }}/${{ env.DOTNET_VERSION }}/${{ matrix.runtime-identifier }}/Spectre.Console.dll'

    - name: Run Infer#
      uses: microsoft/infersharpaction@v1.5
      id: runinfersharp
      with:
        binary-path: 'src/ISTA-Patcher/bin/${{ matrix.configuration }}/${{ env.DOTNET_VERSION }}/${{ matrix.runtime-identifier }}'

    - name: Upload Infer# report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: report-${{ matrix.runtime-identifier }}-${{ matrix.configuration }}
        retention-days: 7
        path: |
          infer-out/report.txt
          infer-out/report.sarif
